import avatarGirl from '../assets/img/avatarGirl.png'
import imgNotAvailable from '../assets/img/imgNotAvailable.jpg';

export const recetas = [
  {
    id: 51231231231,
    time: '30',
    user: {
      username:'Nami', 
      id: '1111', 
      avatar: avatarGirl,
    },
    title: 'Receta 100% natural! pruebalo! se que te encantara tal delicia! asdasd',
    images: [
      { title: 'avatarGirl', src: avatarGirl },
      { title: 'imgNotAvailable', src: imgNotAvailable },
      { title: 'avatarGirl', src: avatarGirl },
      { title: 'imgNotAvailable', src: imgNotAvailable },
      { title: 'avatarGirl', src: avatarGirl },
      { title: 'imgNotAvailable', src: imgNotAvailable },
    ], //'https://www.recetaslamasia.es/wp-content/uploads/2012/10/foto_plato-equilibrado-705x705.jpg',
    date: 'March 25, 2022',
    ingredients: [
      '1 litro de agua', 
      '300gr de espaguetti', 
      'una cucharada de sal', 
      'receta ingrediente 4 porque si y con 300gramosasas', 
      'receta ingrediente 5 porque si y con 300gramosasas', 
      'receta ingrediente 6 porque si y con 300gramosasas', 
      'receta ingrediente 7 porque si y con 300gramosasas', 
      'receta ingrediente 8 porque si y con 300gramosasas',
      'receta ingrediente 9 porque si y con 300gramosasas',
      'receta ingrediente 10 porque si y con 300gramosasa',
    ],
    stars: 325,
    description: 'Pariatur ex magna incididunt occaecat esse aute. Ullamco irure commodo nisi incididunt mollit ut mollit cupidatat laboris sunt esse adipisicing. Veniam pariatur officia ea deserunt adipisicing. Sint et nulla occaecat non pariatur culpa ut ei',
    instruction: 'vierte agua en una olla a una temperatura alta, cuando el agua este caliente, agregue la pasta, espere 10min, saca la pasta del agua y listo!',
    lastUpdated: '3 days ago.',
  },
  {
    id: 112313213123,
    time: '30',
    user: {
      username:'Udyr',
      id: '2222',
      avatar: ''
    },
    title: 'Receta2 amazing!',
    //images: [{title: '', src: ''}],
    date: '18 de agosto 2022',
    ingredients: ['320g de spaguetti', '2 cucharadas de sal'],
    stars: 325,
    description: 'Hesoyam professional Tools aspirine panzer redbull counter strike nissan subaru corea likers another one chupacabra be like this',
    instruction: 'vierte agua en una olla a una temperatura alta, cuando el agua este caliente, agregue la pasta, espere 10min, saca la pasta del agua y listo!',
    lastUpdated: '3 days ago.',
  },
  {
    id: 412312312,
    //avatar: 'url',
    time: '30',
    user: { 
      username: 'Ekko',
      id: '3333',
      avatar: '',
    },
    title: 'Receta6 omg!',
    images: [
      { title: 'imgNotAvailable', src: imgNotAvailable },
      { title: 'imgNotAvailable', src: imgNotAvailable },
      { title: 'imgNotAvailable', src: imgNotAvailable },
    ], //'https://www.recetaslamasia.es/wp-content/uploads/2012/10/foto_plato-equilibrado-705x705.jpg',
    date: '25 de marzo 2022',
    ingredients: ['chicken', 'rice', 'onion'],
    stars: 325,
    description: 'Hesoyam professional Tools aspirine panzer redbull counter strike nissan subaru corea likers another one chupacabra be like this',
    instruction: 'vierte agua en una olla a una temperatura alta, cuando el agua este caliente, agregue la pasta, espere 10min, saca la pasta del agua y listo!',
    lastUpdated: '18 de agosto 2022',
  },
  {
      id: 31233123123123,
      //avatar: 'url',
      time: '30',
      user: {
        username:'Zed',
        id: '4444',
        avatar: '',
      },
      title: 'Receta3 amazing!',
      images: [
        { title: 'imgNotAvailable', src: imgNotAvailable },
      ],
      date: '18 de agosto 2022',
      ingredients: ['spaguetti', 'salt', 'meat'],
      stars: 325,
      description: 'Hesoyam professional Tools aspirine panzer redbull counter strike nissan subaru corea likers another one chupacabra be like this',
      instruction: 'vierte agua en una olla a una temperatura alta, cuando el agua este caliente, agregue la pasta, espere 10min, saca la pasta del agua y listo!',
      lastUpdated: '18 de agosto 2022',
  },
  {
      id: 2123123112,
      //avatar: 'url',
      time: '30',
      user: {
        username: 'Volibear',
        id: '5555',
        avatar: '',
      },
      title: 'Receta4 amazing!',
      images: [
        { title: 'imgNotAvailable', src: imgNotAvailable },
        { title: 'imgNotAvailable', src: imgNotAvailable },
      ],
      date: '18 de agosto 2022',
      ingredients: ['spaguetti', 'salt', 'meat'],
      stars: 325,
      description: 'Hesoyam professional Tools aspirine panzer redbull counter strike nissan subaru corea likers another one chupacabra be like this',
      instruction: 'vierte agua en una olla a una temperatura alta, cuando el agua este caliente, agregue la pasta, espere 10min, saca la pasta del agua y listo!',
      lastUpdated: '18 de agosto 2022',
  },
]